version: "3.3"

services:
  ${artifactId}:
    container_name: ${artifactId}
    image: ${artifactId}
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:postgresql://host.docker.internal:32005/${artifactId}
