spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/${artifactId}
  jpa:
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.com/realms/REALM
          jwk-set-uri: https://keycloak.com/realms/REALM/protocol/openid-connect/certs
logging:
  level:
    org.springframework: INFO
    org.springframework.security: INFO
    root: INFO
    sql: INFO
    web: INFO
