name: Release deploy

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  precheck:
    runs-on: ubuntu-latest
    outputs:
      tag_exists: ${{ steps.tag-check.outputs.exists }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check tag exists
        uses: mukunku/tag-exists-action@v1.6.0
        id: tag-check
        with:
          tag: ${{ github.ref_name }} # v1.2.3

  deploy:
    runs-on: ubuntu-latest
    needs:
      - precheck
    if: needs.precheck.outputs.tag_exists != 'true'
    permissions:
      contents: read
      packages: write
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: ./.github/actions/deploy-maven
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  create-release:
    runs-on: ubuntu-latest
    needs:
      - precheck
      - deploy
    if: needs.precheck.outputs.tag_exists != 'true'
    permissions:
      contents: write
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
