name: Release deploy

on:
  push:
    tags:
      - 'release/v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'maven'

      - name: Read version
        id: version
        run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_OUTPUT"

      - name: Deploy archetype
        run: mvn -B deploy --settings .ci/settings.xml

  create-release:
    runs-on: ubuntu-latest
    needs:
      - deploy
    permissions:
      contents: write
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ needs.deploy.outputs.version }}
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
